---
# Per environment values which override defaults in hmpps-managing-prisoner-apps-staff-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: managing-prisoner-apps-staff-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: 'https://managing-prisoner-apps-staff-dev.hmpps.service.justice.gov.uk'
    HMPPS_AUTH_URL: 'https://sign-in-dev.hmpps.service.justice.gov.uk/auth'
    TOKEN_VERIFICATION_API_URL: 'https://token-verification-api-dev.prison.service.justice.gov.uk'
    COMPONENT_API_URL: 'https://frontend-components-dev.hmpps.service.justice.gov.uk'
    DPS_URL: 'https://dps-dev.prison.service.justice.gov.uk/'
    DPS_PRISONER_URL: 'https://prisoner-dev.digital.prison.service.justice.gov.uk/'
    HMPPS_MANAGE_USERS_API_URL: 'https://manage-users-api-dev.hmpps.service.justice.gov.uk'
    MANAGING_PRISONER_APPS_API_URL: 'https://managing-prisoner-apps-api-dev.hmpps.service.justice.gov.uk'
    PRISON_API_URL: 'https://prison-api-dev.prison.service.justice.gov.uk'
    PERSONAL_RELATIONSHIPS_API_URL: 'https://personal-relationships-api-dev.hmpps.service.justice.gov.uk'
    OS_PLACES_API_URL: 'https://api.os.uk/search/places/v1'
    OS_PLACES_API_KEY: 'Kk3tsS7vujVSiBBLP6UbnqmNLOfPXp1Y'
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: 'true'
    GA4_SITE_ID: 'G-HE5P4PEE48'

generic-prometheus-alerts:
  alertSeverity: hmpps-managing-prisoner-apps-nonprod
